# Generated by Django 4.2.23 on 2025-08-11 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='profile_image',
            field=models.FileField(blank=True, help_text='Upload a profile picture', null=True, upload_to='profile_pics/'),
        ),
    ]
