# Generated by Django 4.2.23 on 2025-08-12 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_alter_userprofile_profile_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='allow_reviews',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='certifications',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='education',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='is_tutor',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='phone_number',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='show_email_publicly',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='website',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='education_and_certifications',
            field=models.TextField(blank=True, help_text='Education background and certifications'),
        ),
    ]
