# Generated by Django 4.2.23 on 2025-08-11 12:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('site_content', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='navigationlist',
            name='list',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='links', to='site_content.page'),
        ),
        migrations.DeleteModel(
            name='NavigationListItem',
        ),
    ]
