# Generated by Django 4.2.23 on 2025-08-11 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_content', '0002_alter_navigationlist_list_delete_navigationlistitem'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='navigationlist',
            name='list',
        ),
        migrations.AddField(
            model_name='navigationlist',
            name='list',
            field=models.ManyToManyField(related_name='links', to='site_content.page'),
        ),
    ]
