# Generated by Django 4.2.23 on 2025-08-01 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='event_spaces',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='listing',
            name='event_spaces_available',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='listing',
            name='short_description',
            field=models.TextField(blank=True),
        ),
    ]
