# Generated by Django 4.2.23 on 2025-08-01 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0002_listing_event_spaces_listing_event_spaces_available_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='updated_on',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
