# Generated by Django 4.2.23 on 2025-08-06 09:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0003_listing_updated_on'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='listing',
            name='event_date_end',
        ),
        migrations.RemoveField(
            model_name='listing',
            name='event_date_start',
        ),
        migrations.RemoveField(
            model_name='listing',
            name='event_spaces',
        ),
        migrations.RemoveField(
            model_name='listing',
            name='event_spaces_available',
        ),
        migrations.CreateModel(
            name='TimeSlot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
                ('event_spaces', models.IntegerField(default=1)),
                ('event_spaces_available', models.IntegerField(default=1)),
                ('is_available', models.BooleanField(default=True)),
                ('status', models.IntegerField(choices=[(0, 'Draft'), (1, 'Published')], default=0)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('listing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='time_slots', to='listings.listing')),
            ],
        ),
    ]
